feat: allow descriptions and pause for all blocks in runbook mode

diff --git a/.github/demos/Dockerfile b/.github/demos/Dockerfile
--- a/.github/demos/Dockerfile
+++ b/.github/demos/Dockerfile
@@ -1,8 +1,8 @@
 FROM ghcr.io/charmbracelet/vhs:v0.2.0
 
-ARG MDRB_VERSION
+ARG MDRB_HASH
 
-RUN [ -z "$MDRB_VERSION" ] && echo "MDRB_VERSION is required" && exit 1 || true
+RUN [ -z "$MDRB_HASH" ] && echo "MDRB_HASH is required" && exit 1 || true
 
 ENV PATH="$PATH:/root/.deno/bin"
 
@@ -11,13 +11,13 @@ RUN echo 'export PATH="$PATH:/root/.deno/bin"' >> ~/.bashrc
 RUN apt install curl unzip bat -y \
   && curl -fsSL https://deno.land/x/install/install.sh | sh
 
-RUN deno install -Arfn mdrb https://deno.land/x/mdrb@${MDRB_VERSION}/mod.ts
+ADD . /vhs/
 
-ADD deno.lock deps.ts deps.dev.ts /tmp/
+RUN deno install -Arfn mdrb /vhs/mod.ts
 
-RUN deno cache --lock=/tmp/deno.lock /tmp/deps.ts /tmp/deps.dev.ts
+RUN deno cache --lock=/vhs/deno.lock /vhs/deps.ts /vhs/deps.dev.ts
 
-RUN mdrb https://deno.land/x/mdrb@${MDRB_VERSION}/demo.md --mode isolated
+RUN mdrb /vhs/demo.md --mode isolated
 
 ENTRYPOINT [] # override parent layer
 
